//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevaplar
    {
        public int id { get; set; }
        public int soruId { get; set; }
        public Nullable<int> sira { get; set; }
        public string cevap { get; set; }
        public bool dogrumu { get; set; }
    
        public virtual sorular sorular { get; set; }
    }
}
