//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class katagoriler
    {
        public katagoriler()
        {
            this.sinavlars = new HashSet<sinavlar>();
            this.sorulars = new HashSet<sorular>();
        }
    
        public int id { get; set; }
        public Nullable<int> ustId { get; set; }
        public string adi { get; set; }
        public string aciklama { get; set; }
        public string tarih { get; set; }
    
        public virtual ICollection<sinavlar> sinavlars { get; set; }
        public virtual ICollection<sorular> sorulars { get; set; }
    }
}
