//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odevDBEntities4 : DbContext
    {
        public odevDBEntities4()
            : base("name=odevDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cevaplar> cevaplars { get; set; }
        public virtual DbSet<katagoriler> katagorilers { get; set; }
        public virtual DbSet<sinavlar> sinavlars { get; set; }
        public virtual DbSet<sorular> sorulars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userSonuc> userSonucs { get; set; }
    }
}
