//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinavlar
    {
        public int id { get; set; }
        public int katId { get; set; }
        public string ad { get; set; }
        public Nullable<bool> testmi { get; set; }
        public Nullable<int> puan { get; set; }
    
        public virtual katagoriler katagoriler { get; set; }
    }
}
