//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorular
    {
        public sorular()
        {
            this.cevaplars = new HashSet<cevaplar>();
        }
    
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> katID { get; set; }
        public int sinavId { get; set; }
        public string soru { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> puan { get; set; }
    
        public virtual ICollection<cevaplar> cevaplars { get; set; }
        public virtual katagoriler katagoriler { get; set; }
        public virtual user user { get; set; }
    }
}
