//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkletOdevBootsRap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.sorulars = new HashSet<sorular>();
            this.userSonucs = new HashSet<userSonuc>();
        }
    
        public int id { get; set; }
        public string yetki { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
    
        public virtual ICollection<sorular> sorulars { get; set; }
        public virtual ICollection<userSonuc> userSonucs { get; set; }
    }
}
